### PR TITLE
Corrected spelling error in 'clarification'

### PR DESCRIPTION
**Pull request by ashleyteow**
@gmmowry Hi Glenna!

### CODE REVIEW

**Comment by gmmowry** [comment]
Hi! When you get into the work place, best practice is to wait to merge a branch into master until you've received the :shipit: from another developer, a senior engineer, your boss, etc. so they have a chance to review the code and ensure it won’t break anything. Just to keep in mind for the future! Looks good! :shipit:

**Comment by ashleyteow** [comment]
Hi Glenna,

Thanks for the tip! Which exercise did I not do this for??

Best,
Ashley

**Comment by gmmowry** [comment]
Just for this one, 1.5 the exercise teaching about pull requests in Github. The rest of the challenges you can merge on your own unless you're awaiting a code review for me on Github. Thanks!

**Comment by ashleyteow** [comment]
Gotcha - will make sure to do that in the future! Also, did you happen to
get my message on Slack - I had a question regarding CSS positioning.

**Pull request merged**
